begin;

-- Public browser clients may only supply the columns used by the forms.
-- IDs and timestamps must always be generated by the database.
revoke insert on table public.applications from anon, authenticated;
grant insert (full_name, email, department, message, type, status)
on table public.applications
to anon, authenticated;

revoke insert on table public.page_views from anon, authenticated;
grant insert (path, session_id)
on table public.page_views
to anon, authenticated;

-- NOT VALID keeps legacy rows from blocking deployment while enforcing these
-- rules for every new or updated row.
alter table public.applications
  drop constraint if exists applications_full_name_length_check,
  drop constraint if exists applications_email_format_check,
  drop constraint if exists applications_department_length_check,
  drop constraint if exists applications_message_length_check,
  drop constraint if exists applications_type_check,
  drop constraint if exists applications_status_check;

alter table public.applications
  add constraint applications_full_name_length_check
    check (char_length(btrim(full_name)) between 2 and 120) not valid,
  add constraint applications_email_format_check
    check (
      email is not null
      and char_length(email) <= 254
      and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    ) not valid,
  add constraint applications_department_length_check
    check (department is null or char_length(btrim(department)) <= 160) not valid,
  add constraint applications_message_length_check
    check (message is not null and char_length(btrim(message)) between 10 and 10000) not valid,
  add constraint applications_type_check
    check (type in ('contact', 'join', 'project')) not valid,
  add constraint applications_status_check
    check (status in ('pending', 'approved', 'rejected')) not valid;

alter table public.page_views
  drop constraint if exists page_views_path_check,
  drop constraint if exists page_views_session_id_check;

alter table public.page_views
  add constraint page_views_path_check
    check (path is not null and char_length(path) between 1 and 200 and path like '/%') not valid,
  add constraint page_views_session_id_check
    check (session_id is not null and char_length(session_id) between 8 and 128) not valid;

create index if not exists applications_email_created_at_idx
  on public.applications (lower(email), created_at desc);

create index if not exists applications_created_at_idx
  on public.applications (created_at desc);

create index if not exists page_views_session_created_at_idx
  on public.page_views (session_id, created_at desc);

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);

-- The trigger runs as its owner so it can count previous submissions even
-- though public visitors cannot SELECT from applications.
create or replace function public.protect_application_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count integer;
  global_count integer;
begin
  new.full_name := btrim(new.full_name);
  new.email := lower(btrim(new.email));
  new.department := nullif(btrim(new.department), '');
  new.message := btrim(new.message);
  new.created_at := now();

  if new.email is null then
    raise exception using
      errcode = '23514',
      message = 'invalid_submission';
  end if;

  -- Serialize requests for the same address so concurrent inserts cannot
  -- race past the limit.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(new.email, 20260903)
  );

  if not public.is_admin() then
    select count(*)
      into global_count
      from public.applications
     where created_at >= now() - interval '1 hour';

    -- This protects database capacity during a broad attack that rotates
    -- addresses. Turnstile remains the stronger production bot defence.
    if global_count >= 100 then
      raise exception using
        errcode = 'P0001',
        message = 'submission_capacity_limit';
    end if;

    select count(*)
      into recent_count
      from public.applications
     where lower(email) = new.email
       and created_at >= now() - interval '1 hour';

    if recent_count >= 3 then
      raise exception using
        errcode = 'P0001',
        message = 'submission_rate_limit';
    end if;

    if exists (
      select 1
        from public.applications
       where lower(email) = new.email
         and type = new.type
         and message = new.message
         and created_at >= now() - interval '24 hours'
    ) then
      raise exception using
        errcode = 'P0001',
        message = 'duplicate_submission';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.protect_application_submission() from public, anon, authenticated;

drop trigger if exists protect_application_submission_trigger on public.applications;
create trigger protect_application_submission_trigger
before insert on public.applications
for each row execute function public.protect_application_submission();

-- Analytics is non-critical, but its public insert endpoint still needs hard
-- bounds so one forged session cannot grow the table without limit.
create or replace function public.protect_page_view_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count integer;
  global_count integer;
begin
  new.path := btrim(new.path);
  new.session_id := btrim(new.session_id);
  new.created_at := now();

  if new.session_id is null then
    raise exception using
      errcode = '23514',
      message = 'invalid_page_view';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(new.session_id, 20260903)
  );

  select count(*)
    into global_count
    from public.page_views
   where created_at >= now() - interval '1 hour';

  if global_count >= 5000 then
    raise exception using
      errcode = 'P0001',
      message = 'page_view_capacity_limit';
  end if;

  select count(*)
    into recent_count
    from public.page_views
   where session_id = new.session_id
     and created_at >= now() - interval '1 hour';

  if recent_count >= 120 then
    raise exception using
      errcode = 'P0001',
      message = 'page_view_rate_limit';
  end if;

  return new;
end;
$$;

revoke all on function public.protect_page_view_submission() from public, anon, authenticated;

drop trigger if exists protect_page_view_submission_trigger on public.page_views;
create trigger protect_page_view_submission_trigger
before insert on public.page_views
for each row execute function public.protect_page_view_submission();

commit;
